// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuaCsXM1RAk521RQZpN3nlZtwoO0Qxjk8',
    appId: '1:29982109672:web:fa61bf2d776d6e7fbc3e5d',
    messagingSenderId: '29982109672',
    projectId: 'alsanafer-6cab7',
    authDomain: 'alsanafer-6cab7.firebaseapp.com',
    storageBucket: 'alsanafer-6cab7.appspot.com',
    measurementId: 'G-1JH3RGKEYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYP6_q3HjQTraUhspEOkQq9ozfVjZProc',
    appId: '1:29982109672:android:bc88f57465d03a40bc3e5d',
    messagingSenderId: '29982109672',
    projectId: 'alsanafer-6cab7',
    storageBucket: 'alsanafer-6cab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc7-ORENvIZrBG37LaMxbAbJfr-TkIxh8',
    appId: '1:29982109672:ios:760737afbb6d6f00bc3e5d',
    messagingSenderId: '29982109672',
    projectId: 'alsanafer-6cab7',
    storageBucket: 'alsanafer-6cab7.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc7-ORENvIZrBG37LaMxbAbJfr-TkIxh8',
    appId: '1:29982109672:ios:cc3527a59ac11a80bc3e5d',
    messagingSenderId: '29982109672',
    projectId: 'alsanafer-6cab7',
    storageBucket: 'alsanafer-6cab7.appspot.com',
    iosBundleId: 'com.example.demoApp.RunnerTests',
  );
}
